name: Gitee Repo

on: [ push, delete, create ]

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SECRET }}
        with:
          source-repo: "git@github.com:iyunx/920930.git"
          destination-repo: "git@gitee.com:iyunx/920930.git"
